# Generated by Django 4.2.3 on 2023-08-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='printer_images/'),
        ),
    ]
