# Generated by Django 4.2.3 on 2023-08-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0002_printer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='printer',
        ),
        migrations.AddField(
            model_name='parts',
            name='printers',
            field=models.ManyToManyField(blank=True, related_name='parts', to='Hub.printer'),
        ),
    ]
