# Generated by Django 4.2.3 on 2023-08-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0003_remove_parts_printer_parts_printers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='filament_needed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='print_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parts',
            name='printers',
            field=models.ManyToManyField(to='Hub.printer'),
        ),
    ]
